FROM python:3.8-buster
COPY . /tmp/canvas_db
WORKDIR /tmp/canvas_db

ARG CANVAS_DB_USER
ARG CANVAS_DB_PASS
ARG CANVAS_DB_SECRET

ENV CANVAS_DB_USER $CANVAS_DB_USER
ENV CANVAS_DB_PASS $CANVAS_DB_PASS
ENV CANVAS_DB_SECRET $CANVAS_DB_SECRET

RUN export CANVAS_DB_SECRET=${CANVAS_DB_SECRET}
RUN export CANVAS_DB_USER=${CANVAS_DB_USER}
RUN export CANVAS_DB_PASS=${CANVAS_DB_PASS}

RUN pip install pipenv

RUN cd /tmp/canvas_db && pipenv install
