version: '3.7'

services:
  web-test:
    build: 
      context: .
      args:
        CANVAS_DB_USER: "${CANVAS_DB_USER}"
        CANVAS_DB_PASS: "${CANVAS_DB_PASS}"
        CANVAS_DB_SECRET: "${CANVAS_DB_SECRET}"
    image: canvas_db
    command: bash -c "./wait-for-it.sh db:5432 && pipenv run python ./manage.py makemigrations && pipenv run python ./manage.py migrate && pipenv run python ./manage.py test --no-input"
    volumes:
      - ./:/tmp/canvas_db
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${CANVAS_DB_USER}
      - POSTGRES_PASSWORD=${CANVAS_DB_PASS}
      - POSTGRES_DB=${CANVAS_DB_USER}
volumes:
  postgres_data:
