# Generated by Django 3.1.3 on 2020-11-17 05:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=30)),
                ('street_name', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=30, validators=[django.core.validators.EmailValidator])),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=4)),
                ('building_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_db.buildingaddress')),
            ],
        ),
        migrations.CreateModel(
            name='LandlordContact',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenant_db.contact')),
                ('position', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
            ],
            bases=('tenant_db.contact',),
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_db.householdaddress')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_db.householdaddress'),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_db.buildingaddress')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_db.landlord')),
            ],
        ),
    ]
