# Generated by Django 3.1.3 on 2020-11-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdaddress',
            name='building_address',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='address',
        ),
        migrations.RemoveField(
            model_name='landlordcontact',
            name='contact_ptr',
        ),
        migrations.RemoveField(
            model_name='building',
            name='address',
        ),
        migrations.RemoveField(
            model_name='building',
            name='landlord',
        ),
        migrations.AddField(
            model_name='building',
            name='postal_code',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='street_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='street_number',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='unit_number',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_db.building'),
        ),
        migrations.DeleteModel(
            name='BuildingAddress',
        ),
        migrations.DeleteModel(
            name='HouseholdAddress',
        ),
        migrations.DeleteModel(
            name='Landlord',
        ),
        migrations.DeleteModel(
            name='LandlordContact',
        ),
    ]
